FROM 552819999234.dkr.ecr.us-east-1.amazonaws.com/espa/external:latest
ENV PREFIX=/usr/local \
    SRC_DIR=/usr/local/src \
    ESPAINC=/usr/local/include \
    ESPALIB=/usr/local/lib \
		L8_AUX_DIR=/usr/local/src \
    HDFINC=$PREFIX/include \
    HDFLIB=$PREFIX/lib \
    HDFLINK="-lmfhdf -ldf -lproj -ljpeg -lz -lsz -lm" \
    GCTPINC=/usr/local/inc


COPY S2/ppS10/consolidate/ /usr/local/S2/ppS10/consolidate

WORKDIR /usr/local/S2/ppS10/consolidate
# RUN make clean && make


